spring.application.name=InternAssignment

server.port=10000



spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=internassignmentdb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
