spring.application.name=InternAssignment

server.port=10000



spring.mongodb.uri=mongodb+srv://ankitvishwakarma9137:Ankit%40123%2B@cluster0.vcbyy.mongodb.net/?retryWrites=true&w=majority
spring.mongodb.database=internassignmentdb
spring.data.mongodb.auto-index-creation=true
spring.main.allow-circular-references=true
