spring.application.name=InternAssignment

server.port=8080
spring.profiles.active=prod

#spring.datasource.url=jdbc:mysql://localhost:3306/user_register
#spring.datasource.password=Ankit@123+
#spring.datasource.username=root
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver